
export default {
    userInfo:{},
    currLists:[],
    appoinLists:[
        {
            time:'2018-12-02',
            contents:[
                {
                    title:'预约1',
                    id:0,
                    isBkColor:false,
                    totalNumber:30,
                    appinInfos:[
                        {
                            name:'张一',
                            userClassify:'vip',
                            sex:'男',
                            email:'744890753@qq.com'
                        },
                        {
                            name:'张一',
                            userClassify:'vip',
                            sex:'男',
                            email:'744890753@qq.com'
                        },
                        {
                            name:'张一',
                            userClassify:'vip',
                            sex:'男',
                            email:'744890753@qq.com'
                        },
                        {
                            name:'张一',
                            userClassify:'vip',
                            sex:'男',
                            email:'744890753@qq.com'
                        },
                        {
                            name:'张一',
                            userClassify:'vip',
                            sex:'男',
                            email:'744890753@qq.com'
                        },
                        {
                            name:'张一',
                            userClassify:'vip',
                            sex:'男',
                            email:'744890753@qq.com'
                        },
                        {
                            name:'张一',
                            userClassify:'vip',
                            sex:'男',
                            email:'744890753@qq.com'
                        },
                        {
                            name:'张一',
                            userClassify:'vip',
                            sex:'男',
                            email:'744890753@qq.com'
                        },
                        {
                            name:'张一',
                            userClassify:'vip',
                            sex:'男',
                            email:'744890753@qq.com'
                        },
                        {
                            name:'张一',
                            userClassify:'vip',
                            sex:'男',
                            email:'744890753@qq.com'
                        },
                        {
                            name:'张一',
                            userClassify:'vip',
                            sex:'男',
                            email:'744890753@qq.com'
                        },
                        {
                            name:'张一',
                            userClassify:'vip',
                            sex:'男',
                            email:'744890753@qq.com'
                        },
                    ]
                },
                {
                    title:'预约2',
                    id:1,
                    isBkColor:false,
                    totalNumber:30,
                    appinInfos:[
                        {
                            name:'张二',
                            userClassify:'vip',
                            sex:'男',
                            email:'744890753@qq.com'
                        },
                        {
                            name:'张二',
                            userClassify:'vip',
                            sex:'男',
                            email:'744890753@qq.com'
                        },
                        {
                            name:'张二',
                            userClassify:'vip',
                            sex:'男',
                            email:'744890753@qq.com'
                        },
                        {
                            name:'张二',
                            userClassify:'vip',
                            sex:'男',
                            email:'744890753@qq.com'
                        },
                        {
                            name:'张二',
                            userClassify:'vip',
                            sex:'男',
                            email:'744890753@qq.com'
                        },
                    ]
                },
                {
                    title:'预约3',
                    id:2,
                    isBkColor:false,
                    totalNumber:30,
                    appinInfos:[
                        {
                            name:'张三',
                            userClassify:'vip',
                            sex:'男',
                            email:'744890753@qq.com'
                        },
                        {
                            name:'张三',
                            userClassify:'vip',
                            sex:'男',
                            email:'744890753@qq.com'
                        },
                        {
                            name:'张三',
                            userClassify:'vip',
                            sex:'男',
                            email:'744890753@qq.com'
                        },
                        {
                            name:'张三',
                            userClassify:'vip',
                            sex:'男',
                            email:'744890753@qq.com'
                        },
                        {
                            name:'张三',
                            userClassify:'vip',
                            sex:'男',
                            email:'744890753@qq.com'
                        },
                        {
                            name:'张三',
                            userClassify:'vip',
                            sex:'男',
                            email:'744890753@qq.com'
                        },
                        {
                            name:'张三',
                            userClassify:'vip',
                            sex:'男',
                            email:'744890753@qq.com'
                        },
                        {
                            name:'张三',
                            userClassify:'vip',
                            sex:'男',
                            email:'744890753@qq.com'
                        },
                        {
                            name:'张三',
                            userClassify:'vip',
                            sex:'男',
                            email:'744890753@qq.com'
                        },
                        {
                            name:'张三',
                            userClassify:'vip',
                            sex:'男',
                            email:'744890753@qq.com'
                        },
                        {
                            name:'张三',
                            userClassify:'vip',
                            sex:'男',
                            email:'744890753@qq.com'
                        },
                        {
                            name:'张三',
                            userClassify:'vip',
                            sex:'男',
                            email:'744890753@qq.com'
                        },
                        {
                            name:'张三',
                            userClassify:'vip',
                            sex:'男',
                            email:'744890753@qq.com'
                        },
                        {
                            name:'张三',
                            userClassify:'vip',
                            sex:'男',
                            email:'744890753@qq.com'
                        },
                        {
                            name:'张三',
                            userClassify:'vip',
                            sex:'男',
                            email:'744890753@qq.com'
                        },
                        {
                            name:'张三',
                            userClassify:'vip',
                            sex:'男',
                            email:'744890753@qq.com'
                        },
                        {
                            name:'张三',
                            userClassify:'vip',
                            sex:'男',
                            email:'744890753@qq.com'
                        },
                        {
                            name:'张三',
                            userClassify:'vip',
                            sex:'男',
                            email:'744890753@qq.com'
                        },
                        {
                            name:'张三',
                            userClassify:'vip',
                            sex:'男',
                            email:'744890753@qq.com'
                        },{
                            name:'张三',
                            userClassify:'vip',
                            sex:'男',
                            email:'744890753@qq.com'
                        },
                        {
                            name:'张三',
                            userClassify:'vip',
                            sex:'男',
                            email:'744890753@qq.com'
                        },
                        {
                            name:'张三',
                            userClassify:'vip',
                            sex:'男',
                            email:'744890753@qq.com'
                        },

                    ]
                },
            ],
            isShow: false
        },
        {
            time:'2018-10-02',
            contents:[
                {
                    title:'预约4',
                    id:0,
                    isBkColor:false,
                    totalNumber:30,
                    appinInfos:[
                        {
                            name:'李一',
                            userClassify:'vip',
                            sex:'男',
                            email:'744890753@qq.com'
                        },
                        {
                            name:'李一',
                            userClassify:'vip',
                            sex:'男',
                            email:'744890753@qq.com'
                        },
                        {
                            name:'李一',
                            userClassify:'vip',
                            sex:'男',
                            email:'744890753@qq.com'
                        },
                        {
                            name:'李一',
                            userClassify:'vip',
                            sex:'男',
                            email:'744890753@qq.com'
                        },
                        {
                            name:'李一',
                            userClassify:'vip',
                            sex:'男',
                            email:'744890753@qq.com'
                        },
                        {
                            name:'李一',
                            userClassify:'vip',
                            sex:'男',
                            email:'744890753@qq.com'
                        },
                        {
                            name:'李一',
                            userClassify:'vip',
                            sex:'男',
                            email:'744890753@qq.com'
                        }
                     ]
                },
                {
                    title:'预约5',
                    id:1,
                    isBkColor:false,
                    totalNumber:30,
                    appinInfos:[
                        {
                            name:'李二',
                            userClassify:'vip',
                            sex:'男',
                            email:'744890753@qq.com'
                        },
                        {
                            name:'李二',
                            userClassify:'vip',
                            sex:'男',
                            email:'744890753@qq.com'
                        },
                        {
                            name:'李二',
                            userClassify:'vip',
                            sex:'男',
                            email:'744890753@qq.com'
                        },
                        {
                            name:'李二',
                            userClassify:'vip',
                            sex:'男',
                            email:'744890753@qq.com'
                        },
                        {
                            name:'李二',
                            userClassify:'vip',
                            sex:'男',
                            email:'744890753@qq.com'
                        },
                        {
                            name:'李二',
                            userClassify:'vip',
                            sex:'男',
                            email:'744890753@qq.com'
                        },
                        {
                            name:'李二',
                            userClassify:'vip',
                            sex:'男',
                            email:'744890753@qq.com'
                        },
                        {
                            name:'李二',
                            userClassify:'vip',
                            sex:'男',
                            email:'744890753@qq.com'
                        },
                        {
                            name:'李二',
                            userClassify:'vip',
                            sex:'男',
                            email:'744890753@qq.com'
                        },
                        {
                            name:'李二',
                            userClassify:'vip',
                            sex:'男',
                            email:'744890753@qq.com'
                        },
                     ]
                },
                {
                    title:'预约6',
                    id:2,
                    isBkColor:false,
                    totalNumber:30,
                    appinInfos:[
                        {
                            name:'李三',
                            userClassify:'vip',
                            sex:'男',
                            email:'744890753@qq.com'
                        },
                        {
                            name:'李三',
                            userClassify:'vip',
                            sex:'男',
                            email:'744890753@qq.com'
                        },
                        {
                            name:'李三',
                            userClassify:'vip',
                            sex:'男',
                            email:'744890753@qq.com'
                        },
                        {
                            name:'李三',
                            userClassify:'vip',
                            sex:'男',
                            email:'744890753@qq.com'
                        },
                        {
                            name:'李三',
                            userClassify:'vip',
                            sex:'男',
                            email:'744890753@qq.com'
                        },
                        {
                            name:'李三',
                            userClassify:'vip',
                            sex:'男',
                            email:'744890753@qq.com'
                        },
                     ]
                },
            ],
            isShow: false
        },
        {
            time:'2018-08-02',
            contents:[
                {
                    title:'预约7',
                    id:0,
                    isBkColor:false,
                    totalNumber:30,
                    appinInfos:[
                        {
                            name:'刘9',
                            userClassify:'vip',
                            sex:'男',
                            email:'744890753@qq.com'
                        },
                        {
                            name:'刘9',
                            userClassify:'vip',
                            sex:'男',
                            email:'744890753@qq.com'
                        },
                    ]
                },
                {
                    title:'预约8',
                    id:1,
                    isBkColor:false,
                    totalNumber:30,
                    appinInfos:[
                        {
                            name:'刘9',
                            userClassify:'vip',
                            sex:'男',
                            email:'744890753@qq.com'
                        },
                        {
                            name:'刘9',
                            userClassify:'vip',
                            sex:'男',
                            email:'744890753@qq.com'
                        },
                    ]
                },
                {
                    title:'预约9',
                    id:2,
                    isBkColor:false,
                    totalNumber:30,
                    appinInfos:[
                        {
                            name:'刘9',
                            userClassify:'vip',
                            sex:'男',
                            email:'744890753@qq.com'
                        },
                        {
                            name:'刘9',
                            userClassify:'vip',
                            sex:'男',
                            email:'744890753@qq.com'
                        },
                    ]
                },
            ],
            isShow: false
        },
    ],//预约情况
    shopClassifys:[]//商品分类
}