export default {
  userInfoL:{},
    currLists:[
        {
            time:'2018-12-02',
            names:[
                {
                    title:'课程1',
                    id:0,
                    isBkColor:false
                },
                {
                    title:'课程2',
                    id:1,
                    isBkColor:false
                },
                {
                    title:'课程3',
                    id:2,
                    isBkColor:false
                },
            ],
            isShow:false
        },
        {
            time:'2018-10-02',
            names:[
                {
                    title:'课程4',
                    id:0,
                    isBkColor:false
                },
                {
                    title:'课程5',
                    id:1,
                    isBkColor:false
                },
                {
                    title:'课程6',
                    id:2,
                    isBkColor:false
                },
            ],
            isShow: false
        },
        {
            time:'2018-08-02',
            names:[
                {
                    title:'课程7',
                    id:0,
                    isBkColor:false
                },
                {
                    title:'课程8',
                    id:1,
                    isBkColor:false
                },
                {
                    title:'课程9',
                    id:2,
                    isBkColor:false
                },
            ],
            isShow: false
        },
    ],//课程列表
    appoinLists:[
        {
            time:'2018-12-02',
            names:[
                {
                    title:'预约1',
                    id:0,
                    isBkColor:false
                },
                {
                    title:'预约2',
                    id:1,
                    isBkColor:false
                },
                {
                    title:'预约3',
                    id:2,
                    isBkColor:false
                },
            ],
            isShow: false
        },
        {
            time:'2018-10-02',
            names:[
                {
                    title:'预约4',
                    id:0,
                    isBkColor:false
                },
                {
                    title:'预约5',
                    id:1,
                    isBkColor:false
                },
                {
                    title:'预约6',
                    id:2,
                    isBkColor:false
                },
            ],
            isShow: false
        },
        {
            time:'2018-08-02',
            names:[
                {
                    title:'预约7',
                    id:0,
                    isBkColor:false
                },
                {
                    title:'预约8',
                    id:1,
                    isBkColor:false
                },
                {
                    title:'预约9',
                    id:2,
                    isBkColor:false
                },
            ],
            isShow: false
        },
    ],//预约情况

}